### ISSUE TITLE
StrumNote.update Bug

### ISSUE THREAD

**Issue by SpadeArcade** [MobilePorting/FNF-PsychEngine-0.6.3-Mobile#10]
### Describe your bug here.

![Screenshot_20240728-051954](https://github.com/user-attachments/assets/72173add-6980-4b29-929b-1a2536ee3109)

### Command Prompt/Terminal logs (if existing)

```bash
Its On The Image
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No I have Been using LUA

**Comment by SantiYea** [comment]
then is not a Engine bug, anything you did maybe it messed smth with the functionality of the Strums.

**Comment by SpadeArcade** [comment]
I know Every Lua I used has Nothing to Do with the Strums

**Comment by SpadeArcade** [comment]
I even tried to replace the assets with the newer assets to see if it stops doing that

**Comment by SpadeArcade** [comment]
And I never messed with the Strums in the First place

**Comment by SantiYea** [comment]
replacing assets doents give you crash by that, is something about some code it is messing with it, check every Lua and see what it does.

**Comment by haeynaa** [comment]
It can also be the json, i alr gor a similar errror but mine had notestrums and note splashes, see if the json is correct following the psych engine, or if u are import a mod, if this json follow the others from the same mod
