### ISSUE TITLE
Could You Make It So Both Psych Engines Can Co-Exist?

### ISSUE THREAD

**Issue by SkeppyTheOne** [MobilePorting/FNF-PsychEngine-0.6.3-Mobile#9]
### What feature do you want to get added on the **base** engine?

If You Already Have The (Amazing) 0.7.3 Port, You Can't Download The 0.6.3 One, And Vice-Versa, So, Could You Make It So Both APKs Can Co-Exist Without Conflicting?

### To test your sight, and reliability, please select the option of what should NOT be requested.

Stage Editor, 6K+ support, and winning icons.

**Comment by moxie-coder** [comment]
buddy, they already can, you just have to know how to rename the save file in the source code

**Comment by moxie-coder** [comment]
otherwise not really

**Comment by SkeppyTheOne** [comment]
> buddy, they already can, you just have to know how to rename the save file in the source code

How Can You Do It? I'm Assuming It Involves Building The APK Using The Source Code In A Way That Allows For Both Apps To Be Installed In The Same Device

**Comment by moxie-coder** [comment]
![image](https://github.com/user-attachments/assets/fe158750-7bd4-44cc-95dc-52ac1d0b9388)
simply change these two lines

**Comment by SkeppyTheOne** [comment]
> ![image](https://private-user-images.githubusercontent.com/124418090/351491196-fe158750-7bd4-44cc-95dc-52ac1d0b9388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3Njg4MTMsIm5iZiI6MTcyMTc2ODUxMywicGF0aCI6Ii8xMjQ0MTgwOTAvMzUxNDkxMTk2LWZlMTU4NzUwLTdiZDQtNDRjYy05NWRjLTUyYWMxZDBiOTM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QyMTAxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWFmYzg5YWU2YmVlNjI0MDNmOTZkOWVmMjUyYTlkZWMyMGM1ZTkzZDkzNGQyMjdjNTliMjZjYmRhODAyYWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gAd5ZIyOIQQhxZIyCHsJBmPyzKn1KrBDYfgeHk99C5Y) simply change these two lines

And Where Are Those? I'm Not Really An Expert, Sorry For The Many Questions xD

**Comment by moxie-coder** [comment]
> > ![image](https://private-user-images.githubusercontent.com/124418090/351491196-fe158750-7bd4-44cc-95dc-52ac1d0b9388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3Njg4MTMsIm5iZiI6MTcyMTc2ODUxMywicGF0aCI6Ii8xMjQ0MTgwOTAvMzUxNDkxMTk2LWZlMTU4NzUwLTdiZDQtNDRjYy05NWRjLTUyYWMxZDBiOTM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QyMTAxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWFmYzg5YWU2YmVlNjI0MDNmOTZkOWVmMjUyYTlkZWMyMGM1ZTkzZDkzNGQyMjdjNTliMjZjYmRhODAyYWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gAd5ZIyOIQQhxZIyCHsJBmPyzKn1KrBDYfgeHk99C5Y) simply change these two lines
> 
> And Where Are Those? I'm Not Really An Expert, Sorry For The Many Questions xD

you need to download the source code and know how to build the project

**Comment by SkeppyTheOne** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/124418090/351491196-fe158750-7bd4-44cc-95dc-52ac1d0b9388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3Njg4MTMsIm5iZiI6MTcyMTc2ODUxMywicGF0aCI6Ii8xMjQ0MTgwOTAvMzUxNDkxMTk2LWZlMTU4NzUwLTdiZDQtNDRjYy05NWRjLTUyYWMxZDBiOTM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QyMTAxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWFmYzg5YWU2YmVlNjI0MDNmOTZkOWVmMjUyYTlkZWMyMGM1ZTkzZDkzNGQyMjdjNTliMjZjYmRhODAyYWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gAd5ZIyOIQQhxZIyCHsJBmPyzKn1KrBDYfgeHk99C5Y) simply change these two lines
> > 
> > 
> > And Where Are Those? I'm Not Really An Expert, Sorry For The Many Questions xD
> 
> you need to download the source code and know how to build the project

Figured It Out, Thank Youuu

**Comment by moxie-coder** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/124418090/351491196-fe158750-7bd4-44cc-95dc-52ac1d0b9388.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3Njg4MTMsIm5iZiI6MTcyMTc2ODUxMywicGF0aCI6Ii8xMjQ0MTgwOTAvMzUxNDkxMTk2LWZlMTU4NzUwLTdiZDQtNDRjYy05NWRjLTUyYWMxZDBiOTM4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QyMTAxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWFmYzg5YWU2YmVlNjI0MDNmOTZkOWVmMjUyYTlkZWMyMGM1ZTkzZDkzNGQyMjdjNTliMjZjYmRhODAyYWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gAd5ZIyOIQQhxZIyCHsJBmPyzKn1KrBDYfgeHk99C5Y) simply change these two lines
> > > 
> > > 
> > > And Where Are Those? I'm Not Really An Expert, Sorry For The Many Questions xD
> > 
> > 
> > you need to download the source code and know how to build the project
> 
> Figured It Out, Thank Youuu

np
